### ISSUE TITLE
Some permissions are missing from the various grant pages

### ISSUE THREAD

**Issue by dang0ld** [project-fifo/cerberus#8]
This is not an exhaustive list, but in particular, I'm trying to be ready for when I have to add an organization's "join" permissions, so I was trying to add this to my user, then to a group.

It looks like once you choose "Organization", then an org, then the specific permissions options are only:
Everything
See
Delete
Edit

.. but not Join.

Here's an example from a role permissions page (but this should probably be allowed anywhere organizations can be selected). And I'm sure there are others that may be missing, I haven't compared the entire list..

![screen shot 2016-05-16 at 11 10 40 am](https://cloud.githubusercontent.com/assets/5656559/15293720/56f8ce46-1b57-11e6-88ad-a1dcec009c21.png)

**Comment by Licenser** [comment]
Hi Dan, this was resolved in 0.8.1 :)
